BANCO_QUESTOES = [
    {"pergunta": "Qual o principal índice de inflação utilizado pelo Banco Central para a meta de inflação?", "opcoes": ["A) IGP-M", "B) IPCA", "C) INCC", "D) Selic"], "correta": "B", "modulo": "Mercado"},
    {"pergunta": "O investidor que busca liquidez imediata e segurança deve priorizar ativos de:", "opcoes": ["A) Renda Variável", "B) Pós-fixados (Selic/CDI)", "C) Criptoativos", "D) Imóveis"], "correta": "B", "modulo": "Mercado"},
    {"pergunta": "No SPIN Selling, uma pergunta de 'Implicação' serve para:", "opcoes": ["A) Saber o nome do gerente do banco", "B) Descobrir o patrimônio total", "C) Aumentar o senso de urgência sobre um problema", "D) Agendar a reunião"], "correta": "C", "modulo": "Vendas"},
    {"pergunta": "Qual a conduta correta ao ouvir 'Já tenho assessor na XP'?", "opcoes": ["A) Desligar o telefone", "B) Oferecer uma segunda opinião técnica sobre a carteira", "C) Falar mal do outro escritório", "D) Tentar convencer a trocar de CPF na hora"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "O que é o FGC?", "opcoes": ["A) Fundo de Garantia de Crédito", "B) Fundo de Gestão de Carteira", "C) Fundo de Garantia do Consumidor", "D) Fundo de Governo Federal"], "correta": "A", "modulo": "Mercado"},
    {"pergunta": "Um SDR deve focar seus esforços em leads que possuem:", "opcoes": ["A) Apenas curiosidade", "B) Perfil de Cliente Ideal (ICP) e dor identificada", "C) Pouco dinheiro mas muito tempo", "D) Nenhuma das anteriores"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "Se a taxa Selic sobe, o que geralmente acontece com a atratividade da Bolsa (Ações)?", "opcoes": ["A) Sobe consideravelmente", "B) Tende a cair, pois a Renda Fixa fica mais atrativa", "C) Não há nenhuma relação", "D) Aumenta o volume de dividendos"], "correta": "B", "modulo": "Mercado"},
    {"pergunta": "Qual o objetivo principal da etapa de 'Rapport'?", "opcoes": ["A) Vender o produto", "B) Gerar conexão e confiança inicial", "C) Pegar o extrato do banco", "D) Falar sobre futebol"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "O termo 'Bull Market' refere-se a um mercado em:", "opcoes": ["A) Queda livre", "B) Estagnação", "C) Tendência de alta", "D) Crise sistêmica"], "correta": "C", "modulo": "Mercado"},
    {"pergunta": "Ao contornar a objeção 'Me manda por e-mail', o SDR deve:", "opcoes": ["A) Mandar o e-mail e nunca mais ligar", "B) Tentar validar um ponto de interesse antes de enviar", "C) Recusar-se a mandar", "D) Pedir o WhatsApp"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "O que caracteriza um investimento Isento de IR para Pessoa Física?", "opcoes": ["A) CDB", "B) Tesouro Direto", "C) LCI e LCA", "D) Debêntures Comuns"], "correta": "C", "modulo": "Mercado"},
    {"pergunta": "A sigla 'LTV' em vendas significa:", "opcoes": ["A) Lead Total Value", "B) Lifetime Value", "C) Low Time View", "D) Lucro Total de Vendas"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "Qual a função básica do CDI no mercado?", "opcoes": ["A) Taxa de empréstimo entre bancos", "B) Taxa de juros do cheque especial", "C) Índice da Bolsa de Nova York", "D) Imposto sobre dividendos"], "correta": "A", "modulo": "Mercado"},
    {"pergunta": "Qual o gatilho mental mais usado ao falar: 'Tenho apenas dois horários na agenda do especialista'?", "opcoes": ["A) Autoridade", "B) Prova Social", "C) Escassez", "D) Reciprocidade"], "correta": "C", "modulo": "Vendas"},
    {"pergunta": "O que é 'Diversificação'?", "opcoes": ["A) Colocar todo o dinheiro no mesmo ativo", "B) Estratégia de diluir riscos em diferentes classes de ativos", "C) Comprar apenas ações de tecnologia", "D) Manter tudo na poupança"], "correta": "B", "modulo": "Mercado"},
    {"pergunta": "No framework Hook-Caption-CTA, o 'CTA' serve para:", "opcoes": ["A) Contar uma história", "B) Chamar para a ação (agendar a reunião)", "C) Prender a atenção", "D) Fazer o diagnóstico"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "Investimentos de Renda Variável são indicados para qual horizonte?", "opcoes": ["A) Reserva de emergência", "B) Médio e Longo Prazo", "C) Gastar no próximo mês", "D) Apenas para day trade"], "correta": "B", "modulo": "Mercado"},
    {"pergunta": "O 'Lead Scoring' ajuda o SDR a:", "opcoes": ["A) Dar notas de 0 a 10 para o cliente", "B) Priorizar os contatos com maior potencial de conversão", "C) Bater a meta de ligações", "D) Organizar a agenda do almoço"], "correta": "B", "modulo": "Vendas"},
    {"pergunta": "O Ibovespa representa:", "opcoes": ["A) A média de todas as empresas do Brasil", "B) O desempenho das ações mais negociadas na B3", "C) A taxa de câmbio do dólar", "D) O lucro total dos bancos brasileiros"], "correta": "B", "modulo": "Mercado"},
    {"pergunta": "A principal função de um SDR na VMB é:", "opcoes": ["A) Fechar o contrato de investimento", "B) Prospectar e qualificar oportunidades para o Assessor", "C) Dar suporte técnico de TI", "D) Fazer a gestão da carteira do cliente"], "correta": "B", "modulo": "Vendas"}
]
]
